build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.23
images:
- dockerfile_literal: "FROM src\n# RUN subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms\n#
    found via https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/p/
    and https://docs.fedoraproject.org/en-US/epel/available-packages/\nRUN dnf install
    -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm\nRUN
    dnf install -y pass || true\nRUN dnf install -y qrencode || true\nRUN dnf install
    -y https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/q/qrencode-4.1.1-1.el9.x86_64.rpm
    https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/q/qrencode-libs-4.1.1-1.el9.x86_64.rpm
    https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/Packages/p/pass-1.7.4-7.el9.noarch.rpm
    || true\nRUN dnf install -y podman \nRUN dnf clean all\n"
  from: src
  to: golang-plus-pass
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  commands: |
    unset GOFLAGS
    HOME=${ARTIFACT_DIR} make test
  container:
    from: golang-plus-pass
- as: verify
  commands: |
    unset GOFLAGS
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
    HOME=${ARTIFACT_DIR} make verify
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: ocm-sdk-go
