base_images:
  nested-podman:
    name: nested-podman
    namespace: ci
    tag: latest
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.23
images:
- dockerfile_literal: |
    FROM nested-podman
    COPY /src /opt/app-root/src
    WORKDIR /opt/app-root/src
    USER root
    RUN dnf install -y git go make
  from: nested-podman
  inputs:
    src:
      paths:
      - destination_dir: src
        source_path: /go/src/github.com/openshift-online/ocm-sdk-go
  to: golang-plus-pass
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: unit
  capabilities:
  - nested-podman
  commands: |
    unset GOFLAGS
    HOME=${ARTIFACT_DIR} make test
  container:
    from: golang-plus-pass
  nested_podman: true
- as: verify
  commands: |
    unset GOFLAGS
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.61.0
    HOME=${ARTIFACT_DIR} make verify
  container:
    from: src
zz_generated_metadata:
  branch: main
  org: openshift-online
  repo: ocm-sdk-go
