label:
  restricted_labels:
    openshift/kubevirt-csi-driver:
    - allowed_teams:
      - aos-staff-engineers
      allowed_users:
      - davidvossel
      - aglitke
      - awels
      label: backport-risk-assessed
    - allowed_teams:
      - aos-staff-engineers
      allowed_users:
      - davidvossel
      - aglitke
      - awels
      assign_on:
      - label: backport-risk-assessed
      label: cherry-pick-approved
plugins:
  openshift/kubevirt-csi-driver:
    plugins:
    - approve
