branch-protection:
  orgs:
    Azure:
      repos:
        ARO-HCP:
          unmanaged: true
tide:
  queries:
  - labels:
    - approved
    - lgtm
    missingLabels:
    - backports/unvalidated-commits
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - jira/invalid-bug
    - needs-rebase
    excludedRepos:
    - Azure/ARO-HCP
    repos:
    - Azure/ARO-HCP
