label:
  restricted_labels:
    openshift/baremetal-runtimecfg:
    - allowed_teams:
      - aos-staff-engineers
      allowed_users:
      - cybertron
      - dougsland
      - mkowalski
      label: backport-risk-assessed
    - allowed_users:
      - amalykhi
      - reihl
      - mffiedler
      - qiowang721
      - zhaozhanqi
      - rbbratta
      - anuragthehatter
      label: cherry-pick-approved
plugins:
  openshift/baremetal-runtimecfg:
    plugins:
    - approve
