base_images:
  base:
    name: "4.3"
    namespace: ocp
    tag: base
binary_build_commands: make
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
promotion:
  name: "4.4"
  namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  name: "4.4"
  namespace: ocp
tests:
- as: e2e-aws
  commands: TEST_SUITE=openshift/conformance/parallel run-tests
  openshift_installer:
    cluster_profile: aws
- as: unit
  commands: make test-unit
  container:
    from: src
