approve:
- commandHelpLink: ""
  repos:
  - openshift/ironic-ipa-downloader
  require_self_approval: false
label:
  restricted_labels:
    openshift/ironic-ipa-downloader:
    - allowed_teams:
      - aos-staff-engineers
      allowed_users:
      - elfosardo
      - dtantsur
      - bfournie
      - iurygregory
      label: backport-risk-assessed
    - allowed_users:
      - pamoedom
      - jadhaj
      - sgoveas
      label: cherry-pick-approved
plugins:
  openshift/ironic-ipa-downloader:
    plugins:
    - approve
